name: Full Deploy to VPS

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          echo "🔁 Pulling latest code..."
          cd webrtc-user-share-camera
          git pull origin main

          echo "📦 Building frontend..."
          cd webrtc-share
          npm install
          npm run build
          pm2 restart 1

          echo "🚀 Restarting backend..."
          cd ../backend
          pm2 restart 0
